In [2]:
import numpy as np

In [2]:
d=np.array([1,2,3])
d

array([1, 2, 3])

In [3]:
a=np.array([1,2,3,4,5])
a[2]

3

In [4]:
a[3]

4

In [5]:
a[1:3]

array([2, 3])

In [6]:
a[-1]

5

In [7]:
#multiindexing
a[[2,3,4]]

array([3, 4, 5])

In [8]:
a.dtype

dtype('int32')

In [10]:
b=np.array([2,3,4],dtype='f')
b

array([2., 3., 4.], dtype=float32)

In [14]:
np.array([2.5,3.4],dtype='i')


array([2, 3], dtype=int32)

In [4]:
g=np.array([2,3,4,5],dtype='S')


In [5]:
g

array([b'2', b'3', b'4', b'5'], dtype='|S1')

In [21]:
g.dtype

dtype('S1')

In [6]:
g

array([b'2', b'3', b'4', b'5'], dtype='|S1')

In [3]:
a=np.array([[1,2,3,4],[8,9,0,4]])

In [4]:
a.shape

(2, 4)

In [5]:
a.ndim

2

In [6]:
a.size

8

In [10]:
b=np.array([
    [
        [1,2,3,4],[8,9,0,4],[6,7,8,3]
    ],
    [
        [1,2,3,4],[8,9,0,4],[4,3,4,6]
    ]
])

In [11]:
b.shape

(2, 3, 4)

In [12]:
b.size

24

In [13]:
b.ndim

3

In [15]:
b=np.array([1,2,3],ndmin=5)

In [16]:
b

array([[[[[1, 2, 3]]]]])

In [17]:
b.shape

(1, 1, 1, 1, 3)

In [18]:
k=np.array([
    [
        [1,2,3,4],[8,9,0,4],[6,7,8,3]
    ],
    [
        [1,2,3,4],[8,9,0,4],[4,3,4,6]
    ]
])

In [28]:
k[0,1,1:2]

array([99])

In [22]:
k[0][1]

array([8, 9, 0, 4])

In [23]:
k[0][2][3]

3

In [24]:
k[0]=0

In [25]:
k

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[1, 2, 3, 4],
        [8, 9, 0, 4],
        [4, 3, 4, 6]]])

In [27]:
k[0][1]=99
k

array([[[ 0,  0,  0,  0],
        [99, 99, 99, 99],
        [ 0,  0,  0,  0]],

       [[ 1,  2,  3,  4],
        [ 8,  9,  0,  4],
        [ 4,  3,  4,  6]]])