In [27]:
import numpy as np

In [2]:
d=np.array([1,2,3])
d

array([1, 2, 3])

In [3]:
a=np.array([1,2,3,4,5])
a[2]

3

In [4]:
a[3]

4

In [5]:
a[1:3]

array([2, 3])

In [6]:
a[-1]

5

In [7]:
#multiindexing
a[[2,3,4]]

array([3, 4, 5])

In [8]:
a.dtype

dtype('int32')

In [10]:
b=np.array([2,3,4],dtype='f')
b

array([2., 3., 4.], dtype=float32)

In [14]:
np.array([2.5,3.4],dtype='i')


array([2, 3], dtype=int32)

In [4]:
g=np.array([2,3,4,5],dtype='S')


In [5]:
g

array([b'2', b'3', b'4', b'5'], dtype='|S1')

In [21]:
g.dtype

dtype('S1')

In [6]:
g

array([b'2', b'3', b'4', b'5'], dtype='|S1')

In [3]:
a=np.array([[1,2,3,4],[8,9,0,4]])

In [4]:
a.shape

(2, 4)

In [5]:
a.ndim

2

In [6]:
a.size

8

In [10]:
b=np.array([
    [
        [1,2,3,4],[8,9,0,4],[6,7,8,3]
    ],
    [
        [1,2,3,4],[8,9,0,4],[4,3,4,6]
    ]
])

In [11]:
b.shape

(2, 3, 4)

In [12]:
b.size

24

In [13]:
b.ndim

3

In [15]:
b=np.array([1,2,3],ndmin=5)

In [16]:
b

array([[[[[1, 2, 3]]]]])

In [17]:
b.shape

(1, 1, 1, 1, 3)

In [18]:
k=np.array([
    [
        [1,2,3,4],[8,9,0,4],[6,7,8,3]
    ],
    [
        [1,2,3,4],[8,9,0,4],[4,3,4,6]
    ]
])

In [28]:
k[0,1,1:2]

array([99])

In [22]:
k[0][1]

array([8, 9, 0, 4])

In [23]:
k[0][2][3]

3

In [24]:
k[0]=0

In [25]:
k

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[1, 2, 3, 4],
        [8, 9, 0, 4],
        [4, 3, 4, 6]]])

In [27]:
k[0][1]=99
k

array([[[ 0,  0,  0,  0],
        [99, 99, 99, 99],
        [ 0,  0,  0,  0]],

       [[ 1,  2,  3,  4],
        [ 8,  9,  0,  4],
        [ 4,  3,  4,  6]]])

In [8]:
import numpy as np
s=np.array([1,3,5])


# summary statistics


In [10]:
s.std()

1.632993161855452

In [11]:
s.mean()

3.0

In [12]:
s.var()

2.6666666666666665

In [13]:
s.sum()

9

###summary statistics in 2d array

In [3]:
a=np.array([[1,2,3,4],[8,9,0,4]])

In [20]:
a.sum()

31

In [21]:
a.mean()

3.875

In [4]:
a.sum(axis=0)

array([ 9, 11,  3,  8])

In [5]:
a.sum(axis=1)

array([10, 21])

In [7]:
a=np.arange(4)
b=np.array([1,5,9,0])
a+b

array([ 1,  6, 11,  3])

In [9]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.empty((5,2))

array([[ 0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  5.98807563e-321],
       [ 0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000, -1.03216423e-310]])

In [15]:
a>=2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
a=np.array([0,1,2,3])
a[a>2]

array([3])

In [20]:
a=np.arange(3)
a.sum()

3

In [21]:
np.sum(a)

3

In [22]:
a**2

array([0, 1, 4], dtype=int32)

In [36]:
from numpy import random
a=random.randint(20)
a


14

In [37]:
random.rand(5)

array([0.35277672, 0.72019787, 0.82018536, 0.27238282, 0.25739033])

In [40]:
b=random.rand(2,3)

In [45]:
b.sort()
b

array([[0.32651975, 0.52811901, 0.80439847],
       [0.01752983, 0.16644611, 0.44859218]])

In [49]:
k=np.array([5,1,9])
k.sort()
k

array([1, 5, 9])

In [53]:
np.sort(k)

array([1, 5, 9])